INSERT INTO vehicletype (id, cubic_capacity, vehicle_type) VALUES
  (0,0,'CARRO'),
  (1,150,'MOTO');
  
INSERT INTO vehicle_registration (check_in_time,check_out_time,vehicle_plate,status,total_value,vehicle_type)
VALUES  
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,0),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1),
  (current_timestamp(),current_timestamp(),'AAAAAA',0,0,1);